package api.entity;
// Generated Apr 13, 2016 10:13:33 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CoreContent generated by hbm2java
 */
@Entity
@Table(name = "CORE_CONTENT")
public class CoreContent{

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "SEQ_CORE_CONTENT", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	private long id;

	@Column(name = "LANGUAGE_ID")
	private long languageId;

	

	@Column(name = "CONTENT_CODE", unique = true, nullable = false, length = 255)
	private String contentCode;

//	@EscapseJava
	@Column(name = "CONTENT")
	private String content;

	public CoreContent() {
	}



	public CoreContent(long languageId, String contentCode, String content) {
		this.languageId = languageId;
		this.contentCode = contentCode;
		this.content = content;
	}

	public CoreContent(long id, long languageId, String contentCode, String content) {
		super();
		this.id = id;
		this.languageId = languageId;
		this.contentCode = contentCode;
		this.content = content;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}


	public String getContentCode() {
		return this.contentCode;
	}

	public void setContentCode(String contentCode) {
		this.contentCode = contentCode;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getLanguageId() {
		return languageId;
	}

	public void setLanguageId(long languageId) {
		this.languageId = languageId;
	}

}
